### ISSUE TITLE
Standardize loading for auditory data

### ISSUE THREAD

**Issue by adwaykanhere** [neurodata/df-dn-paper#43]

**Comment by adwaykanhere** [comment]
By standardizing the code I mean refactoring the code such that it follows PyTorch's Dataset and Dataloader primitives. This can help add transforms/augmentations more easily.

**Comment by PSSF23** [comment]
I see, is this only for auditory? If so I would specify in the title.

**Comment by adwaykanhere** [comment]
I will do it for Auditory first, but technically this should extend to images as well.

**Comment by PSSF23** [comment]
I don't think we will use the package directly but this one might be useful: https://github.com/eonu/torch-fsdd
