### ISSUE TITLE
Stratify Tabular sample sets across class labels

### ISSUE THREAD

**Issue by PSSF23** [neurodata/df-dn-paper#56]
Code that needs to be changed:

https://github.com/neurodata/df-dn-paper/blob/0a7d4470fff0c92f9578a6e663cc0ba6541add3a/benchmarks/tabular/toolbox.py#L53-L76

Code that can be used as a reference:

https://github.com/neurodata/df-dn-paper/blob/0a7d4470fff0c92f9578a6e663cc0ba6541add3a/benchmarks/vision/toolbox.py#L184-L209

@NogaMudrik

**Comment by NogaMudrik** [comment]
I am working on it

**Comment by NogaMudrik** [comment]
I think that maybe the function description is not so accurate
